using System.Collections.Generic;

namespace cManagement.Models
{
    /// <summary>
    /// ViewModel to capture and relay error details in MVC views.
    /// Useful for displaying request ID and multiple error messages.
    /// </summary>
    public class ErrorViewModel
    {
        /// <summary>
        /// Unique request identifier to trace error occurrences.
        /// Automatically generated by ASP.NET Core.
        /// </summary>
        public string? RequestId { get; set; }

        /// <summary>
        /// Indicates whether the RequestId should be displayed in the UI.
        /// </summary>
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        /// <summary>
        /// A list of error messages to display to the user.
        /// </summary>
        public List<string> Messages { get; set; } = new();
    }
}
