name: .NET CI (Ubuntu)

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Ensure compatibility with .NET 8

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Publish build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: cmanagement-artifacts
          path: |
            ./cManagement/bin/Release/net8.0/publish/
            ./cManagement/TestResults/
